name: Application Releases

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Sming Framework
      run: |
         cd /tmp
         git clone https://github.com/SmingHub/Sming.git
         cd Sming/Sming
         export SMING_HOME=$(pwd)
         ../Tools/install.sh all
    - name: Check Coding Style
      env: 
        SMING_HOME: /tmp/Sming/Sming
        SMING_ARCH: Host
      run: |
        make cs
        DIFFS=$(git diff)
        if [ -n "$DIFFS" ]; then
          echo "!!! Coding Style issues Found!!!"
          echo "    Run: 'make cs' to fix them. "
          echo "$DIFFS"
          exit 1
        fi
    - name: Compile Application for ESP8266
      env: 
        SMING_HOME: /tmp/Sming/Sming
        SMING_ARCH: Esp8266
      run: |
        source $SMING_HOME/../Tools/export.sh
        make fetch UPnP-Schema || echo "Done"
        make SMING_ARCH=$SMING_ARCH python-requirements
        make
    - name: Compile Application for Host
      env: 
        SMING_HOME: /tmp/Sming/Sming
        SMING_ARCH: Host
      run: |
        source $SMING_HOME/../Tools/export.sh
        make SMING_ARCH=$SMING_ARCH
    - name: Deplpy new release
      env: 
        SMING_HOME: /tmp/Sming/Sming
        SMING_ARCH: Esp8266
      run: |
        source $SMING_HOME/../Tools/export.sh
        export TAG_VERSION=$(git describe --tags --abbrev=0)
        export RELEASE_VERSION=(${TAG_VERSION//./ })
        export APP_VERSION="${RELEASE_VERSION[0]}.${RELEASE_VERSION[1]}"
        make SMING_ARCH=$SMING_ARCH APP_VERSION=$APP_VERSION APP_VERSION_PATCH=${RELEASE_VERSION[2]}
        make -C $SMING_HOME/Libraries/OtaUpgradeMqtt/tools/deployer SMING_ARCH=Host
        make ota-pack OTA_PATCH_VERSION=${RELEASE_VERSION[2]}
        make ota-deploy MQTT_FIRMWARE_URL=mqtts://${{ secrets.RELEASE_SECRET }}@attachix.com:8883/a/switch/u/${RELEASE_VERSION[0]}.${RELEASE_VERSION[1]} 
         
