name: Application Releases

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Sming Framework
      run: |
         cd /tmp
         git clone https://github.com/SmingHub/Sming.git
         cd Sming/Sming
         export SMING_HOME=$(pwd)
         ../Tools/install.sh all
    - name: Check Coding Style
      env: 
        SMING_HOME: /tmp/Sming/Sming
        SMING_ARCH: Host
      run: |
        make cs
        DIFFS=$(git diff)
        if [ -n "$DIFFS" ]; then
          echo "!!! Coding Style issues Found!!!"
          echo "    Run: 'make cs' to fix them. "
          echo "$DIFFS"
          exit 1
        fi
    - name: Compile Application for ESP8266
      env: 
        SMING_HOME: /tmp/Sming/Sming
        SMING_ARCH: Esp8266
      run: |
        source $SMING_HOME/../Tools/export.sh
        make fetch UPnP-Schema || echo "Done"
        make SMING_ARCH=$SMING_ARCH python-requirements
        make
    - name: Compile Application for Host
      env: 
        SMING_HOME: /tmp/Sming/Sming
        SMING_ARCH: Host
      run: |
        source $SMING_HOME/../Tools/export.sh
        make SMING_ARCH=$SMING_ARCH
    - name: Deploy new release
      env: 
        SMING_HOME: /tmp/Sming/Sming
        SMING_ARCH: Esp8266
        RELEASE_TOKEN: ${{ secrets.RELEASE_SECRET }}
      run: |
        # Setup networking
        sudo ip tuntap add dev tap0 mode tap user $(whoami)
        sudo ip a a dev tap0 192.168.13.1/24
        sudo ip link set tap0 up
        export INTERNET_IF=eth0
        sudo sysctl net.ipv4.ip_forward=1
        sudo sysctl net.ipv6.conf.default.forwarding=1
        sudo sysctl net.ipv6.conf.all.forwarding=1
        sudo iptables -t nat -A POSTROUTING -o "$INTERNET_IF" -j MASQUERADE
        sudo iptables -A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
        sudo iptables -A FORWARD -i tap0 -o "$INTERNET_IF" -j ACCEPT
        sudo ethtool -K "$INTERNET_IF" tx off rx off
        # Main logic
        set -x
        export TAG_VERSION=$(git describe --tags --abbrev=0)
        export RELEASE_VERSION=(${TAG_VERSION//./ })
        export APP_VERSION="${RELEASE_VERSION[0]}.${RELEASE_VERSION[1]}"
        make SMING_ARCH=$SMING_ARCH APP_VERSION=$APP_VERSION APP_VERSION_PATCH=${RELEASE_VERSION[2]}
        make -C $SMING_HOME/Libraries/OtaUpgradeMqtt/tools/deployer SMING_ARCH=Host
        make ota-pack OTA_PATCH_VERSION=${RELEASE_VERSION[2]}
        make ota-deploy MQTT_FIRMWARE_URL=mqtts://$RELEASE_TOKEN@attachix.com:8883/a/switch/u/${RELEASE_VERSION[0]}.${RELEASE_VERSION[1]}